Cli docs
greenpress/docs pull request #31
Opened 2020-12-10 09:40 UTC by or-yam

refernce from the redme file on greenpress-cli repo.
- change some of the styling to mach the docs site.
- removed the note about `greenpress start` command on windows.
- added note about `greenpress populate` command on node V15.

2020-12-11 16:18 UTC, drorrose requested changes

2020-12-11 16:18 UTC, drorrose commented on docs/tools/cli.md
> +### **start**
debug is not supported anymore

2020-12-11 16:18 UTC, drorrose commented on docs/tools/cli.md
> +supported services:
would move this line up to the top of the page (after installation, before describing commands), as it is crucial for both local option of start and for service create

2020-12-11 16:18 UTC, drorrose commented on docs/tools/cli.md
> +- `--from <theme>` set base theme to be used
--from=<theme>, wouldn't work without the equation mark

2020-12-11 16:18 UTC, drorrose commented on docs/tools/cli.md
> +- debug: keeps the start process alive and display live application logs.
not supported anymore

2020-12-11 18:47 UTC, or-yam commented on docs/tools/cli.md
> +supported services:
did you mean to move  the  whole service comand section ?

2020-12-11 19:32 UTC, drorrose requested changes

2020-12-11 19:32 UTC, drorrose commented on docs/tools/cli.md
> +- auth, admin, assets, secrets, content, front
mailing is missing

2020-12-11 19:32 UTC, drorrose commented on docs/tools/cli.md
> +For commands that accepts a service_name as parameter, the supported services are:
give it a title, will be easier to read

2020-12-11 19:32 UTC, drorrose commented on docs/tools/cli.md
> +`greenpress theme my-theme --from classic`
why did you change it? it was correct

2020-12-11 19:55 UTC, drorrose requested changes

2020-12-11 19:55 UTC, drorrose commented on docs/tools/cli.md
> +## For using a specific services
a specific service/ using specific services

2020-12-11 20:02 UTC, drorrose approved these changes

2020-12-12 16:21 UTC, davidmeirlevy approved these changes

2020-12-12 16:21 UTC, merged